name: Deploy Hugo site to Pages

on:
  push: # 当有代码推送到 main 分支时触发
    branches:
      - main
  pull_request:

permissions:
  content: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # 重要！用于拉取主题子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 如果使用扩展版主题功能，需要设为 true

      - name: Build
        run: hugo --minify # 构建并压缩输出

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # 仅在主分支推送时部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hugo 默认的输出目录
          # cname: www.yourdomain.com # 如果你有自定义域名，在此配置